name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        run: rsync -av --progress --exclude='node_modules' --exclude='vendor' --exclude='resources/fonts' --exclude='resources/images' --exclude='resources/scripts' --exclude='resources/styles' --exclude='.github' --exclude='.git' .  ${{ secrets.DEPLOY_PATH }}
